# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Verti < Formula
  desc "Versioned artifacts for Git repositories"
  homepage "https://github.com/ruinivist/verti"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ruinivist/verti/releases/download/v0.2.2/verti_0.2.2_darwin_amd64.tar.gz"
      sha256 "50d51a09a67ddb92085d9a9d924ebef6fda531d3fe2ef084582c6de47a109e93"

      define_method(:install) do
        bin.install "verti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ruinivist/verti/releases/download/v0.2.2/verti_0.2.2_darwin_arm64.tar.gz"
      sha256 "07a3438280c38a0c4f4e017832c547849ed7396e9ac2ccfc23294567beffd2c5"

      define_method(:install) do
        bin.install "verti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ruinivist/verti/releases/download/v0.2.2/verti_0.2.2_linux_amd64.tar.gz"
      sha256 "e0efb51ad468a28e4ed26d3c964a7fba198a49a97d2f0b3f17b2c0c5e96b86b7"
      define_method(:install) do
        bin.install "verti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ruinivist/verti/releases/download/v0.2.2/verti_0.2.2_linux_arm64.tar.gz"
      sha256 "c6837fb79d455918ad92b23e89821e35fa5ccd964ea98def22108428ae87fffd"
      define_method(:install) do
        bin.install "verti"
      end
    end
  end

  test do
    system "#{bin}/verti", "--version"
  end
end
