# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Verti < Formula
  desc "Versioned artifacts for Git repositories"
  homepage "https://github.com/ruinivist/verti"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ruinivist/verti/releases/download/v0.2.3/verti_0.2.3_darwin_amd64.tar.gz"
      sha256 "3de81732ec7b311e808ec61fd567d7dfd2f10f51ecb210e2e5d536cad092269d"

      define_method(:install) do
        bin.install "verti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ruinivist/verti/releases/download/v0.2.3/verti_0.2.3_darwin_arm64.tar.gz"
      sha256 "ca4fcacf558cf8b5bf0a84057fc19c1741faf83cba9f32e7d71c33d822be2f2d"

      define_method(:install) do
        bin.install "verti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ruinivist/verti/releases/download/v0.2.3/verti_0.2.3_linux_amd64.tar.gz"
      sha256 "596f4528989837b333e11c4fa5f3bf81a7f4d7a764cdc085ae6420c4c7413acd"
      define_method(:install) do
        bin.install "verti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ruinivist/verti/releases/download/v0.2.3/verti_0.2.3_linux_arm64.tar.gz"
      sha256 "4afc095eb20e67937170ea6b2e9a739007651cb2f3d44f377d60ce2df94ab482"
      define_method(:install) do
        bin.install "verti"
      end
    end
  end

  test do
    system "#{bin}/verti", "--version"
  end
end
